# 语言
language: java
#mvnw权限配置
before_install:
  - chmod +x mvnw
# 执行脚本
script: "./mvnw clean package -Dmaven.javadoc.skip=true -B -V"
# 通知
notifications:
  email:
    recipients:
      - 2373319771@qq.com
    on_success: always # default: change
    on_failure: always # default: always
# 缓存
cache:
  directories:
    - '$HOME/.m2/repository'

branches:
  only:
    - master
